image: node:18

stages:
  - lint
  - build

cache:
  paths:
    - node_modules/

before_script:
  - npm install

lint:
  stage: lint
  script:
    - npm run code-check

build:
  stage: build
  script:
    - npm run build